version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-fpm
      - image: circleci/mysql:5.6
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_USER: testuser
          - MYSQL_PASSWORD: testpassword
          - MYSQL_DATABASE: testdatabase
          - MYSQL_ROOT_HOST: '%'

    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt update 
      - run: sudo apt install -y default-mysql-client
      - run:
          name: Build image
          command: docker build -t php-container -f Dockerfile .

      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - run:
          name: Test container
          command: docker run php-container sh -c "ls"

      - run: 
          name: Test database connection 
          command: docker run php-container sh -c "php /var/www/connection.php" 